import React, { useRef, useState } from 'react';
import { ActivityIndicator, Animated, Platform, StatusBar, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { WebView } from 'react-native-webview';
import { signOut } from 'firebase/auth';
import ReportModal from '../components/ReportModal';
import { auth } from '../config/firebase';

const COLORS = { bg: '#07090f', surface: '#0d1117', border: '#1e2530', accent: '#1a6bff', accentLight: '#7ab4ff', success: '#30e890', danger: '#ff3737', warning: '#ffbb30', textPrimary: '#e0e8f0', textSecondary: '#8899aa' };
type RiskLevel = 'high' | 'medium' | 'low';
interface Zone { id: string; name: string; description: string; risk: RiskLevel; lat: number; lng: number; incidents: number; lastUpdate: string; tips: string[]; }

const ZONES: Zone[] = [
  { id: 'centro', name: 'Centro', description: 'Alta actividad delictiva nocturna', risk: 'high', lat: 32.5149, lng: -117.0382, incidents: 47, lastUpdate: 'Hace 2 horas', tips: ['Evita transitar después de las 10 PM', 'Mantén tus pertenencias seguras', 'Usa rutas iluminadas'] },
  { id: 'la_mesa', name: 'La Mesa', description: 'Zona residencial con incidentes ocasionales', risk: 'medium', lat: 32.72, lng: -117.02, incidents: 18, lastUpdate: 'Hace 5 horas', tips: ['Precaución en horarios nocturnos', 'Reporta actividad sospechosa'] },
  { id: 'otay-centenario', name: 'Otay-Centenario', description: 'Zona industrial con cruces fronterizos', risk: 'high', lat: 32.55, lng: -116.92, incidents: 38, lastUpdate: 'Hace 1 hora', tips: ['No uses el celular en la vía pública', 'Viaja acompañado'] },
  { id: 'playas_de_tijuana', name: 'Playas de Tijuana', description: 'Zona turística con bajo riesgo', risk: 'low', lat: 32.53, lng: -117.12, incidents: 5, lastUpdate: 'Hace 8 horas', tips: ['Zona relativamente segura', 'Precaución normal en playa'] },
  { id: 'san_antonio_de_los_buenos', name: 'San Antonio de los Buenos', description: 'Zona residencial tranquila', risk: 'low', lat: 32.495, lng: -117.065, incidents: 7, lastUpdate: 'Hace 6 horas', tips: ['Zona de bajo riesgo', 'Mantén precaución básica'] },
  { id: 'sanchez_taboada', name: 'Sánchez Taboada', description: 'Zona con incidentes moderados', risk: 'medium', lat: 32.505, lng: -116.99, incidents: 22, lastUpdate: 'Hace 3 horas', tips: ['Precaución en estacionamientos', 'Usa transporte seguro de noche'] },
  { id: 'cerro_colorado', name: 'Cerro Colorado', description: 'Zona residencial con riesgo moderado', risk: 'medium', lat: 32.54, lng: -116.97, incidents: 15, lastUpdate: 'Hace 4 horas', tips: ['Seguro de día, precaución de noche', 'Usa taxis de aplicación'] },
  { id: 'la_presa', name: 'La Presa', description: 'Zona periférica con incidentes altos', risk: 'high', lat: 32.56, lng: -116.89, incidents: 33, lastUpdate: 'Hace 2 horas', tips: ['Evita zonas apartadas', 'Viaja en grupo', 'Reporta incidentes'] },
  { id: 'la_presa_este', name: 'La Presa Este', description: 'Zona periférica con riesgo moderado', risk: 'medium', lat: 32.52, lng: -116.86, incidents: 12, lastUpdate: 'Hace 7 horas', tips: ['Precaución básica', 'Evita circular de noche solo'] },
];
const RISK_CONFIG = { high: { color: COLORS.danger, label: 'ALTO', fillOpacity: 0.35 }, medium: { color: COLORS.warning, label: 'MEDIO', fillOpacity: 0.3 }, low: { color: COLORS.success, label: 'BAJO', fillOpacity: 0.25 } };

export default function MapScreen({ navigation }: any) {
  const [selectedZone, setSelectedZone] = useState<Zone | null>(null);
  const [filter, setFilter] = useState<RiskLevel | 'all'>('all');
  const [showLegend, setShowLegend] = useState(false);
  const [showReport, setShowReport] = useState(false);
  const [mapLoading, setMapLoading] = useState(true);
  const slideAnim = useRef(new Animated.Value(400)).current;
  const filteredZones = filter === 'all' ? ZONES : ZONES.filter(z => z.risk === filter);

  const mapHTML = `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1.0"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><style>html,body,#map{width:100%;height:100%;margin:0;background:#07090f}.leaflet-control-zoom,.leaflet-control-attribution{display:none}.leaflet-tile-pane{filter:brightness(.75) saturate(.5) hue-rotate(200deg)}</style></head><body><div id="map"></div><script>const map=L.map('map',{center:[32.520,-117.010],zoom:11,zoomControl:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);const zones=${JSON.stringify(filteredZones)};const cfg=${JSON.stringify(RISK_CONFIG)};zones.forEach(z=>{const c=cfg[z.risk];L.circleMarker([z.lat,z.lng],{radius:22,color:c.color,fillColor:c.color,fillOpacity:.35,weight:2}).addTo(map).bindTooltip(z.name+' · '+c.label,{permanent:true,direction:'top'}).on('click',()=>window.ReactNativeWebView.postMessage(JSON.stringify({id:z.id})));});</script></body></html>`;

  const openPanel = (zone: Zone) => { setSelectedZone(zone); Animated.spring(slideAnim, { toValue: 0, useNativeDriver: true, tension: 65, friction: 11 }).start(); };
  const closePanel = () => { Animated.timing(slideAnim, { toValue: 400, duration: 250, useNativeDriver: true }).start(() => setSelectedZone(null)); };
  const handleMessage = (event: any) => { const zone = ZONES.find(z => z.id === JSON.parse(event.nativeEvent.data).id); if (zone) openPanel(zone); };
  const handleLogout = async () => { await signOut(auth); navigation.replace('Login'); };

  return (
    <View style={styles.root}>
      <StatusBar barStyle="light-content" backgroundColor={COLORS.bg} />
      <WebView style={styles.map} source={{ html: mapHTML }} onMessage={handleMessage} javaScriptEnabled originWhitelist={['*']} onLoadEnd={() => setMapLoading(false)} />
      {mapLoading && <View style={styles.loadingOverlay}><ActivityIndicator color={COLORS.accent} size="large" /></View>}
      <View style={styles.header}><View style={styles.logoRow}><View style={styles.logoBox}><Text style={styles.logoText}>SZ</Text></View><View><Text style={styles.headerTitle}>SafeZone</Text><Text style={styles.headerSub}>Tijuana · {filteredZones.length} delegaciones</Text></View></View><View style={styles.headerBtns}><TouchableOpacity style={styles.headerBtn} onPress={() => navigation.navigate('RiskDashboard')}><Text style={styles.headerBtnText}>⚖</Text></TouchableOpacity><TouchableOpacity style={styles.headerBtn} onPress={() => setShowLegend(v => !v)}><Text style={styles.headerBtnText}>☰</Text></TouchableOpacity><TouchableOpacity style={[styles.headerBtn, { borderColor: 'rgba(255,55,55,0.5)' }]} onPress={handleLogout}><Text style={[styles.headerBtnText, { color: COLORS.danger }]}>Salir</Text></TouchableOpacity></View></View>
      {showLegend && <View style={styles.legendPanel}><Text style={styles.legendTitle}>Delegaciones de Tijuana</Text>{(['high', 'medium', 'low'] as RiskLevel[]).map(r => <View key={r} style={styles.legendRow}><View style={[styles.legendDot, { backgroundColor: RISK_CONFIG[r].color }]} /><Text style={styles.legendText}>Riesgo {RISK_CONFIG[r].label}</Text></View>)}</View>}
      <View style={styles.filterRow}>{(['all', 'high', 'medium', 'low'] as const).map(f => <TouchableOpacity key={f} style={[styles.filterBtn, filter === f && styles.filterBtnActive]} onPress={() => setFilter(f)}><Text style={[styles.filterText, filter === f && styles.filterTextActive]}>{f === 'all' ? 'Todas' : RISK_CONFIG[f].label}</Text></TouchableOpacity>)}</View>
      {!selectedZone && <TouchableOpacity style={styles.fabReport} onPress={() => setShowReport(true)}><Text style={styles.fabReportIcon}>🚨</Text><Text style={styles.fabReportText}>Reportar</Text></TouchableOpacity>}
      {selectedZone && <Animated.View style={[styles.panel, { transform: [{ translateY: slideAnim }] }]}><View style={styles.panelHandle} /><View style={styles.panelHeader}><View style={[styles.riskBadge, { borderColor: RISK_CONFIG[selectedZone.risk].color + '55' }]}><Text style={[styles.riskBadgeText, { color: RISK_CONFIG[selectedZone.risk].color }]}>RIESGO {RISK_CONFIG[selectedZone.risk].label}</Text></View><TouchableOpacity onPress={closePanel}><Text style={styles.closeBtnText}>✕</Text></TouchableOpacity></View><Text style={styles.panelName}>{selectedZone.name}</Text><Text style={styles.panelDesc}>{selectedZone.description}</Text><View style={styles.statsRow}><View style={styles.statBox}><Text style={[styles.statNum, { color: RISK_CONFIG[selectedZone.risk].color }]}>{selectedZone.incidents}</Text><Text style={styles.statLabel}>Incidentes</Text></View><View style={styles.statBox}><Text style={styles.statNum}>{selectedZone.lastUpdate}</Text><Text style={styles.statLabel}>Actualizado</Text></View></View><Text style={styles.tipsTitle}>Recomendaciones</Text>{selectedZone.tips.map(tip => <Text key={tip} style={styles.tipText}>› {tip}</Text>)}<View style={styles.actionRow}><TouchableOpacity style={styles.btnReport} onPress={() => setShowReport(true)}><Text style={styles.btnReportText}>🚨 Reportar incidente</Text></TouchableOpacity><TouchableOpacity style={styles.btnRoute}><Text style={styles.btnRouteText}>Ruta alternativa →</Text></TouchableOpacity></View></Animated.View>}
      <ReportModal visible={showReport} onClose={() => setShowReport(false)} zoneName={selectedZone?.name ?? ''} zoneId={selectedZone?.id ?? ''} zoneLat={selectedZone?.lat ?? 0} zoneLng={selectedZone?.lng ?? 0} />
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.bg }, map: { flex: 1 }, loadingOverlay: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.bg },
  header: { position: 'absolute', top: 0, left: 0, right: 0, paddingTop: Platform.OS === 'ios' ? 54 : 44, paddingBottom: 12, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: 'rgba(7,9,15,0.92)', borderBottomWidth: 1, borderBottomColor: COLORS.border }, logoRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, logoBox: { width: 36, height: 36, borderRadius: 10, backgroundColor: COLORS.accent, alignItems: 'center', justifyContent: 'center' }, logoText: { fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace', fontSize: 14, fontWeight: '700', color: '#fff' }, headerTitle: { fontSize: 16, fontWeight: '700', color: COLORS.textPrimary, letterSpacing: 1 }, headerSub: { fontSize: 11, color: COLORS.textSecondary, marginTop: 1 }, headerBtns: { flexDirection: 'row', gap: 6 }, headerBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: COLORS.border, backgroundColor: 'rgba(255,255,255,0.05)' }, headerBtnText: { fontSize: 12, color: COLORS.accentLight, fontWeight: '500' },
  legendPanel: { position: 'absolute', top: Platform.OS === 'ios' ? 110 : 100, right: 16, backgroundColor: 'rgba(13,17,23,0.97)', borderWidth: 1, borderColor: COLORS.border, borderRadius: 14, padding: 14, gap: 6 }, legendTitle: { fontSize: 11, fontWeight: '700', color: COLORS.textSecondary, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 4 }, legendRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, legendDot: { width: 10, height: 10, borderRadius: 5 }, legendText: { fontSize: 12, color: COLORS.textPrimary },
  filterRow: { position: 'absolute', top: Platform.OS === 'ios' ? 110 : 100, left: 16, flexDirection: 'row', gap: 6, flexWrap: 'wrap' }, filterBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: COLORS.border, backgroundColor: 'rgba(13,17,23,0.9)' }, filterBtnActive: { backgroundColor: 'rgba(26,107,255,0.25)', borderColor: 'rgba(26,107,255,0.6)' }, filterText: { fontSize: 12, color: COLORS.textSecondary, fontWeight: '600' }, filterTextActive: { color: COLORS.accentLight },
  fabReport: { position: 'absolute', bottom: 32, right: 16, backgroundColor: COLORS.danger, borderRadius: 28, paddingHorizontal: 18, paddingVertical: 14, flexDirection: 'row', alignItems: 'center', gap: 8 }, fabReportIcon: { fontSize: 18 }, fabReportText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  panel: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: COLORS.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderTopWidth: 1, borderColor: COLORS.border, padding: 20, paddingBottom: 36 }, panelHandle: { width: 36, height: 4, borderRadius: 2, backgroundColor: COLORS.border, alignSelf: 'center', marginBottom: 16 }, panelHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }, riskBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6, borderWidth: 1 }, riskBadgeText: { fontSize: 11, fontWeight: '700', letterSpacing: 0.8 }, closeBtnText: { fontSize: 16, color: COLORS.textSecondary }, panelName: { fontSize: 20, fontWeight: '700', color: COLORS.textPrimary, marginBottom: 4 }, panelDesc: { fontSize: 13, color: COLORS.textSecondary, marginBottom: 16 }, statsRow: { flexDirection: 'row', gap: 10, marginBottom: 20 }, statBox: { flex: 1, backgroundColor: '#111820', borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, padding: 12, alignItems: 'center' }, statNum: { fontSize: 18, fontWeight: '700', color: COLORS.textPrimary, marginBottom: 2 }, statLabel: { fontSize: 11, color: COLORS.textSecondary }, tipsTitle: { fontSize: 13, fontWeight: '600', color: COLORS.textSecondary, marginBottom: 10, textTransform: 'uppercase', letterSpacing: 0.5 }, tipText: { fontSize: 13, color: COLORS.textPrimary, lineHeight: 20 }, actionRow: { flexDirection: 'row', gap: 10, marginTop: 16 }, btnReport: { flex: 1, paddingVertical: 13, borderRadius: 12, borderWidth: 1, borderColor: COLORS.border, backgroundColor: 'rgba(255,55,55,0.1)', alignItems: 'center' }, btnReportText: { fontSize: 13, fontWeight: '600', color: COLORS.danger }, btnRoute: { flex: 1, paddingVertical: 13, borderRadius: 12, backgroundColor: COLORS.accent, alignItems: 'center' }, btnRouteText: { fontSize: 13, fontWeight: '700', color: '#fff' },
});
